/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package idv.lance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void test_module_init_message() {
        Module module = new Module();
        String response = module.print();
        assertEquals(response, "Shape:(C)ircle or (R)ectangle?");
    }

    @Test
    void test_module_input_R_message() {
        Module module = new Module();
        module.input("R");
        String response = module.print();
        assertEquals(response, "Rectangle Side A length?");
    }

    @Test
    public void test_input_R_and_5_then_return_message() {
        Module module = new Module();
        module.input("R");
        module.input("5");
        String response = module.print();
        assertEquals(response, "Rectangle Side B length?");
    }
}
